webtalk_init -webtalk_dir C:/Users/thara/Documents/signal_gen/signal_gen.sim/sim_1/behav/xsim/xsim.dir/Signal_gen_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Sep  9 04:16:01 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cdfd80c0-447f-4920-a34a-31b7ea611779" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "eb9a114500714e23ba06912778fec767" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1190 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "182377955 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15464_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1097275224 -regid "" -xml C:/Users/thara/Documents/signal_gen/signal_gen.sim/sim_1/behav/xsim/xsim.dir/Signal_gen_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/thara/Documents/signal_gen/signal_gen.sim/sim_1/behav/xsim/xsim.dir/Signal_gen_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/thara/Documents/signal_gen/signal_gen.sim/sim_1/behav/xsim/xsim.dir/Signal_gen_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
